<?php  return array (
  'categories' => 'Categories',
  'category_confirm_delete' => 'Are you sure you want to remove this category? All elements in this category will be filed to uncategorized.',
  'category_create' => 'Create Category',
  'category_err_ae' => 'A category already exists with that name. Please try a different name.',
  'category_err_create' => 'An error occurred while trying to create the category.',
  'category_err_not_found' => 'Category not found!',
  'category_err_nf' => 'Category not found.',
  'category_err_nfs' => 'Category not found with key: %s',
  'category_err_ns' => 'Category not specified.',
  'category_err_ns_name' => 'Please specify a valid category name.',
  'category_err_remove' => 'An error occurred while trying to remove the category.',
  'category_err_save' => 'An error occurred while trying to save the category.',
  'category_existing' => 'Existing Category',
  'category_heading' => 'Category',
  'category_msg' => 'Here you can view and edit all resources grouped by category.',
  'category_no_chunks' => 'No chunks for this category.',
  'category_no_plugins' => 'No plugins for this category.',
  'category_no_snippets' => 'No snippets for this category.',
  'category_no_templates' => 'No templates for this category.',
  'category_no_template_variables' => 'No template variables for this category.',
  'category_rename' => 'Rename Category',
  'category_remove' => 'Remove Category',
);