<?php  return array (
  'binary' => 'Binary',
  'binary_desc' => 'Is the file a binary file or text/ascii?',
  'content_type' => 'Content Type',
  'content_type_desc' => 'Content Types are specific filesystem types for your resources. Here you can manage them, as well as associate them with a file extension.',
  'content_type_err_nf' => 'Content Type not found.',
  'content_type_err_nfs' => 'Content type with ID [[+id]] not found.',
  'content_type_err_ns' => 'Content Type not specified.',
  'content_type_err_ns_name' => 'Please specify a valid name for the Content Type.',
  'content_type_err_create' => 'An error occurred while trying to create the Content Type.',
  'content_type_err_in_use' => 'You cannot remove this Content Type, as it is currently in use by Resources in MODX. Please re-assign the Content Types of those Resources before proceeding.',
  'content_type_err_remove' => 'An error occurred while trying to remove the Content Type.',
  'content_type_err_save' => 'An error occurred while trying to save the Content Type.',
  'content_type_header' => 'Header',
  'content_type_main_tab' => 'Main',
  'content_type_header_tab' => 'Custom headers',
  'content_type_header_title' => 'Create/edit header',
  'content_type_new' => 'New Content Type',
  'content_type_remove' => 'Delete Content Type',
  'content_type_remove_confirm' => 'Are you sure you want to delete this Content Type?',
  'content_types' => 'Content Types',
  'file_extensions' => 'File Extension',
  'file_extensions_desc' => 'This is the specified file extension for this Content Type.',
);