<?php  return array (
  'login_language' => 'Language',
  'login_activation_key_err' => 'Activation key does not match! Please check your activation email and make sure you loaded the right URL.',
  'login_blocked_admin' => 'You have been blocked from the manager by an administrator.',
  'login_blocked_error' => 'You are temporarily blocked and cannot log in. Please try again later.',
  'login_blocked_ip' => 'You are not allowed to login from your current IP address.',
  'login_blocked_time' => 'You are not allowed to login at this time. Please try again later.',
  'login_blocked_too_many_attempts' => 'You have been blocked due to too many failed login attempts.',
  'login_button' => 'Login',
  'login_cannot_locate_account' => 'The username or password you entered is incorrect.  Please check the username, re-type the password, and try again.',
  'login_copyright' => '&copy; 2005-2014 by <a href="http://modx.com/about/" target="_blank">MODX, LLC</a>. MODX Revolution&trade; is licensed under the GPLv2 or later.',
  'login_email_label' => 'Account Email:',
  'login_err_unknown' => 'An unknown error occurred while trying to log in.',
  'login_forget_your_login' => 'Forgot your Login?',
  'login_hostname_error' => 'Your hostname does not point back to your IP address.',
  'login_message' => 'Please enter your login credentials to start your Manager session. Your username and password are case-sensitive, so please enter them carefully!',
  'login_password' => 'Password',
  'login_password_reset_act_sent' => 'Password Reset Activation email sent. Please check your inbox.',
  'login_remember' => 'Remember me',
  'login_send_activation_email' => 'Send Activation Email',
  'login_title' => 'MODX CMF Manager Login',
  'login_user_err_nf_email' => 'User not found with that email or username. Please try again.',
  'login_username' => 'Username',
  'login_username_or_email' => 'Username or Email',
  'login_username_password_incorrect' => 'The username or password you entered is incorrect.  Please check the username, re-type the password, and try again.',
  'login_user_inactive' => 'Your user account has been disabled. Please contact your system administrator to enable the account.',
);