<?php if(time() > 1423055633){return array();} return array (
  'assets_path' => '/home/sta/public_html/styleguide/docroot/assets/',
  'assets_url' => '/styleguide/assets/',
  'cache_disabled' => 'false',
  'compress_js' => 1,
  'config_options' => 
  array (
  ),
  'connectors_path' => '/home/sta/public_html/styleguide/docroot/connectors/',
  'connectors_path_auto' => 0,
  'connectors_url' => '/styleguide/connectors/',
  'connectors_url_auto' => 0,
  'context_connectors_path' => '/home/sta/public_html/styleguide/docroot/connectors/',
  'context_connectors_url' => '/styleguide/connectors/',
  'context_mgr_path' => '/home/sta/public_html/styleguide/docroot/manager/',
  'context_mgr_url' => '/styleguide/manager/',
  'context_web_path' => '/home/sta/public_html/styleguide/docroot/',
  'context_web_url' => '/styleguide/',
  'core_path' => '/home/sta/public_html/styleguide/core/',
  'database_charset' => 'latin1',
  'database_connection_charset' => 'latin1',
  'database_dsn' => 'mysql:host=localhost;dbname=sta_styleguide;charset=latin1',
  'database_password' => '***REMOVED***',
  'database_server' => 'localhost',
  'database_type' => 'mysql',
  'database_user' => 'sta_styleguide',
  'dbase' => 'sta_styleguide',
  'driver_options' => 
  array (
  ),
  'http_host' => 'www.savethearctic.org',
  'https_port' => '443',
  'inplace' => '1',
  'installmode' => 1,
  'language' => 'en',
  'mgr_path' => '/home/sta/public_html/styleguide/docroot/manager/',
  'mgr_path_auto' => 0,
  'mgr_url' => '/styleguide/manager/',
  'mgr_url_auto' => 0,
  'processors_path' => '/home/sta/public_html/styleguide/core/model/modx/processors/',
  'server_dsn' => 'mysql:host=localhost;charset=latin1',
  'site_sessionname' => 'SN549a51ec5f08f',
  'table_prefix' => 'modx_',
  'unpacked' => 0,
  'web_path' => '/home/sta/public_html/styleguide/docroot/',
  'web_path_auto' => 0,
  'web_url' => '/styleguide/',
  'web_url_auto' => 0,
);